FOGL-8980: Support multiple DNP3 outstations
fledge-iot/fledge-south-dnp3 pull request #43
Opened 2024-08-06 10:25 UTC by pintomax

FOGL-8980: Support multiple DNP3 outstations

2024-08-06 10:55 UTC, MarkRiddoch submitted a review, later dismissed
Looks good to me. We need to update the documentation for the plugin

2024-08-06 21:46 UTC, praveen-garg commented on plugin.cpp
> +					"options" : [ "integer","float", "boolean" ],
?

2024-08-06 21:46 UTC, praveen-garg commented on plugin.cpp
> +					"displayName" : "Link id",
ID

2024-08-07 09:47 UTC, praveen-garg reviewed
1) As we have list of outstations so remove old config i.e. Outstation address, port, link id

2) Consider upgrade basic test and deprecate old config items

2024-08-07 09:47 UTC, praveen-garg commented on plugin.cpp
> +		"displayName" : "Outstations list",
Remove the word _list_

2024-08-07 15:03 UTC, pintomax commented
> 1. As we have list of outstations so remove old config i.e. Outstation address, port, link id
> 2. Consider upgrade basic test and deprecate old config items

We have decided to keep basic configuration for the time being.

If array values are set into "outstations", those will be used

2024-08-07 15:04 UTC, praveen-garg commented
> > 1. As we have list of outstations so remove old config i.e. Outstation address, port, link id
> > 2. Consider upgrade basic test and deprecate old config items
> 
> We have decided to keep basic configuration for the time being.
> 
> If array values are set into "outstations", those will be used

Only Outstations list value will be used, Or this existing will be considered as well?

2024-08-07 15:08 UTC, pintomax commented
> > > 1. As we have list of outstations so remove old config i.e. Outstation address, port, link id
> > > 2. Consider upgrade basic test and deprecate old config items
> > 
> > 
> > We have decided to keep basic configuration for the time being.
> > If array values are set into "outstations", those will be used
> 
> Only Outstations list value will be used, Or this existing will be considered as well?

The existing config (one outstation) can be left there for compatibility.

If list is set and we have at least one element, the one outstation config will be ignored.

We have to update the documentation, possibly logging an info message in this case

2024-08-08 13:18 UTC, MarkRiddoch requested changes
Just a couple of minor things. Also we need to update the documentation to describe the configuration with the list versus the older, individual strings.

2024-08-08 13:18 UTC, MarkRiddoch commented on dnp3.cpp
> +			Logger::getLogger()->error("Error '%s' type 'list' item is not an arrary",
Typo: array -> array

2024-08-08 13:18 UTC, MarkRiddoch commented on dnp3.cpp
> +				Logger::getLogger()->error(">>> %s: %s", key.c_str(), value.c_str());
This is not a meaningful error to report - is this debug that has been left in?

2024-08-08 15:09 UTC, pintomax commented
Still need to update configuration for
- single outstation and multiple outstations
- application data logging in debug log

2024-08-09 08:34 UTC, MarkRiddoch commented
> 1. As we have list of outstations so remove old config i.e. Outstation address, port, link id
> 2. Consider upgrade basic test and deprecate old config items

The old configuration items are present for reasons of backward compatibility. They allow for people to upgrade without breaking a current installation. The documentation will discuss how to move to the newer list if required.

2024-08-09 08:38 UTC, MarkRiddoch approved these changes
Lets raise a separate Jira to update the documentation

2024-08-13 09:38 UTC, Mohit04tomar commented
I’m getting following error when connection of foglamp to the DNP3 Outstation is lost:
```
Aug 13 14:00:48 foglamp-VirtualBox FogLAMP snp #1[13227]: INFO: master_1 - Begining task: Application Poll
Aug 13 14:00:53 foglamp-VirtualBox FogLAMP snp #1[13227]: WARNING: master_1 - Timeout waiting for response
Aug 13 14:01:02 foglamp-VirtualBox FogLAMP snp #1[13227]: WARNING: master_1 - Link status request - response timeout
Aug 13 14:01:53 foglamp-VirtualBox FogLAMP snp #1[13227]: INFO: master_1 - Begining task: Application Poll
Aug 13 14:01:58 foglamp-VirtualBox FogLAMP snp #1[13227]: WARNING: master_1 - Timeout waiting for response
Aug 13 14:02:02 foglamp-VirtualBox FogLAMP snp #1[13227]: WARNING: master_1 - Link status request - response timeout
Aug 13 14:02:58 foglamp-VirtualBox FogLAMP snp #1[13227]: INFO: master_1 - Begining task: Application Poll
Aug 13 14:03:02 foglamp-VirtualBox FogLAMP snp #1[13227]: WARNING: master_1 - Link status request - response timeout
Aug 13 14:03:03 foglamp-VirtualBox FogLAMP snp #1[13227]: WARNING: master_1 - Timeout waiting for response

```
And when the network of DNP3 Outstation is up again, foglamp-south-dnp3 is still giving the same error and requires disable/enable of south service of foglamp-south-dnp3 to start ingestion of data again.

Note: It was working fine in the 2.5.0 and nightly

2024-08-13 11:05 UTC, pintomax commented
Pkease share exact steps for the disconnection test and the simulator you’re using.This branch does not have re connection improvements yetOn 13 Aug 2024, at 11:39, Mohit04tomar ***@***.***> wrote:﻿
I’m getting following error when connection of foglamp to the DNP3 Outstation is lost:
Aug 13 14:00:48 foglamp-VirtualBox FogLAMP snp #1[13227]: INFO: master_1 - Begining task: Application Poll
Aug 13 14:00:53 foglamp-VirtualBox FogLAMP snp #1[13227]: WARNING: master_1 - Timeout waiting for response
Aug 13 14:01:02 foglamp-VirtualBox FogLAMP snp #1[13227]: WARNING: master_1 - Link status request - response timeout
Aug 13 14:01:53 foglamp-VirtualBox FogLAMP snp #1[13227]: INFO: master_1 - Begining task: Application Poll
Aug 13 14:01:58 foglamp-VirtualBox FogLAMP snp #1[13227]: WARNING: master_1 - Timeout waiting for response
Aug 13 14:02:02 foglamp-VirtualBox FogLAMP snp #1[13227]: WARNING: master_1 - Link status request - response timeout
Aug 13 14:02:58 foglamp-VirtualBox FogLAMP snp #1[13227]: INFO: master_1 - Begining task: Application Poll
Aug 13 14:03:02 foglamp-VirtualBox FogLAMP snp #1[13227]: WARNING: master_1 - Link status request - response timeout
Aug 13 14:03:03 foglamp-VirtualBox FogLAMP snp #1[13227]: WARNING: master_1 - Timeout waiting for response


And when the network of DNP3 Outstation is up again, foglamp-south-dnp3 is still giving the same error and requires disable/enable of south service of foglamp-south-dnp3 to start ingestion of data again.
Note: It was working fine in the 2.5.0 and nightly

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-08-14 06:33 UTC, pintomax commented
@Mohit04tomar 
Could you please add exact steps  for the disconnection tests?

All the needed details would help to reproduce this in my scenario.

It's not clear "connection is lost" and "connection is up again"

Please note in this PR there is also log for connection but no new code related to connection handling.

Also add:
- version of opendnp3 library you compiled wtih plugin with
- which DNP3 simulator you are using

2024-08-14 07:16 UTC, Mohit04tomar commented
> @Mohit04tomar Could you please add exact steps for the disconnection tests?
> 
> All the needed details would help to reproduce this in my scenario.
> 
> It's not clear "connection is lost" and "connection is up again"
> 
> Please note in this PR there is also log for connection but no new code related to connection handling.
> 
> Also add:
> 
> * version of opendnp3 library you compiled wtih plugin with
> * which DNP3 simulator you are using

Steps to reproduce:
1. Setup and Start the DNP3 simulator (Fryr SCADA DNP3 simulator)
2. Add south service of south-dnp3 with valid config in enable mode
3. Check data ingestion (GOOD)
4. Disconnect the network of DNP3 simulator machine
5. Check syslog of FogLAMP

```Aug 13 14:00:48 foglamp-VirtualBox FogLAMP snp #1[13227]: INFO: master_1 - Begining task: Application Poll
Aug 13 14:00:53 foglamp-VirtualBox FogLAMP snp #1[13227]: WARNING: master_1 - Timeout waiting for response
Aug 13 14:01:02 foglamp-VirtualBox FogLAMP snp #1[13227]: WARNING: master_1 - Link status request - response timeout
Aug 13 14:01:53 foglamp-VirtualBox FogLAMP snp #1[13227]: INFO: master_1 - Begining task: Application Poll
Aug 13 14:01:58 foglamp-VirtualBox FogLAMP snp #1[13227]: WARNING: master_1 - Timeout waiting for response
Aug 13 14:02:02 foglamp-VirtualBox FogLAMP snp #1[13227]: WARNING: master_1 - Link status request - response timeout
Aug 13 14:02:58 foglamp-VirtualBox FogLAMP snp #1[13227]: INFO: master_1 - Begining task: Application Poll
Aug 13 14:03:02 foglamp-VirtualBox FogLAMP snp #1[13227]: WARNING: master_1 - Link status request - response timeout
Aug 13 14:03:03 foglamp-VirtualBox FogLAMP snp #1[13227]: WARNING: master_1 - Timeout waiting for response
```
6. Reconnect network of DNP3 Simulator

Actual Result: Data ingestion does not start again, and above logs are still repeating in syslog.
Expected Result: Data ingestion should start again without any issue.


**Note:** south-dnp3 plugin is compiled and packaged using the OpenDNP3 library, as specified in the requirements.sh file, version 2.3.0, for Ubuntu 20.

2024-08-14 07:52 UTC, pintomax commented
@Mohit04tomar 

what really "Disconnect the network of DNP3 simulator machine" means?

Disconnect the ethernet cable? Something else?

Please add the details in one go

2024-08-14 10:11 UTC, Mohit04tomar commented
@pintomax Simply turn off the Internet on the machine having simulator installed

2024-08-14 10:25 UTC, pintomax commented
@Mohit04tomar please verify the network cable disconnection works with multiple outstations as well

2024-08-14 10:46 UTC, pintomax commented
@Mohit04tomar I tested 2 outstations:

- outstation windows with freyrScada simulator: network unplugged
- outstation-demo unix with 'sudo iptables -A OUTPUT -p tcp --destination-port 20001 -j DROP'


cable back on windows: OK
sudo iptables -F on linux: OK

This KeepAliveFailure detection seems OK


Maybe we can decrease verbosity of changed netwowk status to debug after reconnection

2024-08-14 11:39 UTC, pintomax commented
@Mohit04tomar latest commit addresses FOGL-9019

2024-08-15 12:25 UTC, praveen-garg commented
@pintomax I would suggest to have [39e1a7a](https://github.com/fledge-iot/fledge-south-dnp3/pull/43/commits/39e1a7a27aafd3ae4c1825f8d47897ce02aa474b) fix against _develop_. Test, merge & close that Jira that. Then update this branch.

2024-08-16 17:35 UTC, MarkRiddoch approved these changes
Looks good as far as I can tell. TVA need this so we need to get this merged and tested as soon as we can, without compromising testing. Don't mind if you roll both Jirs's together or seperate them. Both Jiras are needed and need the same level of testing.

2024-08-22 12:22 UTC, praveen-garg commented
@pintomax  I have 2 outstations and stopped one of them i.e. Outstation ID 3.
Log says:
`Aug 22 17:06:25 nerdl2-Latitude-3420-2 FogLAMP dnp3 #1[192632]: WARNING: dnp3 #1_remote_3 - End of file`

There should be **meaningful** warning with outstation details.

2024-08-22 16:25 UTC, pintomax commented
Filtering out received log messages:

Aug 22 18:17:57 ubuntu20-lenovo Fledge DN1[95598]: WARNING: Outstation id 10 - Connection errored or closed

2024-08-23 09:00 UTC, praveen-garg approved these changes
Thanks @pintomax

2024-08-23 09:01 UTC, merged